[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "JAX_BSSN"
version = "0.0.1"
description = "A 3D BSSN Numerical Relativity code using JAX"
authors = [
    { name = "Christopher Woolford", email = "clwoolford@wisc.edu" }
]
license = { file = "LICENSE" }

dependencies = [
    "jax",
    "jaxlib",
    "numpy",
    "matplotlib",
    "openPMD-api",
]

[project.optional-dependencies]
demos = [
    "tqdm",
]
test = [
    "pytest",
    "scipy",
]

[tool.setuptools]
packages = [
    "JAX_BSSN",
    "JAX_BSSN.bssn",
    "JAX_BSSN.cartoon",
    "JAX_BSSN.cartoon.axisymmetry",
    "JAX_BSSN.cartoon.spherical_symmetry",
    "JAX_BSSN.diagnostics",
    "JAX_BSSN.evolution",
    "JAX_BSSN.fmr",
    "JAX_BSSN.utilities",
]
