"""Second-order Maxwell fields coupled to the JAX BSSN spacetime solver."""

from JAX_BSSN.EM.cartoon import (
    axisymmetric_einstein_maxwell_rk4_step,
    axisymmetric_prescribed_wave_rk4_step,
    cartoon_prescribed_wave_rk4_step,
    compact_axisymmetric_wave,
    compact_cartoon_wave,
    compute_axisymmetric_constraint_divergences,
    compute_axisymmetric_einstein_maxwell_rhs,
    compute_axisymmetric_prescribed_rhs,
    compute_cartoon_constraint_divergences,
    compute_cartoon_prescribed_rhs,
    compute_spherical_einstein_maxwell_rhs,
    expand_axisymmetric_wave_plane,
    expand_cartoon_wave_axis,
    fill_axisymmetric_wave_ghosts,
    fill_cartoon_wave_ghosts,
    project_axisymmetric_wave_rhs,
    project_cartoon_wave_rhs,
    reconstruct_axisymmetric_wave_support,
    reconstruct_cartoon_wave_support,
    spherical_einstein_maxwell_rk4_step,
    validate_axisymmetric_wave_grid,
    validate_cartoon_wave_grid,
)
from JAX_BSSN.EM.diagnostics import electromagnetic_output_fields
from JAX_BSSN.EM.energy_momentum import (
    ElectromagneticStressEnergy,
    compute_electromagnetic_energy_momentum,
    compute_electromagnetic_stress_energy,
)
from JAX_BSSN.EM.equations import (
    compute_em_rhs,
    source_free_projected_field_dots,
)
from JAX_BSSN.EM.evolve import (
    compute_einstein_maxwell_rhs,
    einstein_maxwell_rk4_step,
    evolve_einstein_maxwell_steps,
    evolve_prescribed_em_steps,
    prescribed_em_rk4_step,
)
from JAX_BSSN.EM.flrw import (
    FLRWParameters,
    flrw_background,
    flrw_exact_fields,
)
from JAX_BSSN.EM.geometry import compute_bssn_em_geometry
from JAX_BSSN.EM.initial_data import (
    conformal_vector_to_physical_covector,
    contract_conformal_electromagnetic_fields,
    electromagnetic_hamiltonian_residual,
    electromagnetic_hamiltonian_source,
    linearized_electromagnetic_hamiltonian_operator,
    linearized_electromagnetic_hamiltonian_source,
    off_centered_toroidal_electric_seed,
    solve_electromagnetic_conformal_factor,
)
from JAX_BSSN.EM.variables import (
    BSSNEMGeometry,
    EinsteinMaxwellVariables,
    EMVariables,
)


__all__ = [
    "BSSNEMGeometry",
    "EinsteinMaxwellVariables",
    "ElectromagneticStressEnergy",
    "EMVariables",
    "FLRWParameters",
    "axisymmetric_einstein_maxwell_rk4_step",
    "axisymmetric_prescribed_wave_rk4_step",
    "cartoon_prescribed_wave_rk4_step",
    "compact_axisymmetric_wave",
    "compact_cartoon_wave",
    "compute_axisymmetric_constraint_divergences",
    "compute_axisymmetric_einstein_maxwell_rhs",
    "compute_axisymmetric_prescribed_rhs",
    "compute_bssn_em_geometry",
    "compute_cartoon_constraint_divergences",
    "compute_cartoon_prescribed_rhs",
    "compute_einstein_maxwell_rhs",
    "compute_electromagnetic_energy_momentum",
    "compute_electromagnetic_stress_energy",
    "compute_em_rhs",
    "compute_spherical_einstein_maxwell_rhs",
    "conformal_vector_to_physical_covector",
    "contract_conformal_electromagnetic_fields",
    "einstein_maxwell_rk4_step",
    "electromagnetic_hamiltonian_residual",
    "electromagnetic_hamiltonian_source",
    "electromagnetic_output_fields",
    "evolve_einstein_maxwell_steps",
    "evolve_prescribed_em_steps",
    "expand_axisymmetric_wave_plane",
    "expand_cartoon_wave_axis",
    "fill_axisymmetric_wave_ghosts",
    "fill_cartoon_wave_ghosts",
    "flrw_background",
    "flrw_exact_fields",
    "linearized_electromagnetic_hamiltonian_operator",
    "linearized_electromagnetic_hamiltonian_source",
    "off_centered_toroidal_electric_seed",
    "prescribed_em_rk4_step",
    "project_axisymmetric_wave_rhs",
    "project_cartoon_wave_rhs",
    "reconstruct_axisymmetric_wave_support",
    "reconstruct_cartoon_wave_support",
    "solve_electromagnetic_conformal_factor",
    "source_free_projected_field_dots",
    "spherical_einstein_maxwell_rk4_step",
    "validate_axisymmetric_wave_grid",
    "validate_cartoon_wave_grid",
]
